// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Greeter.proto

package com.minhdtb.demo.protos;

public final class GreeterOuterClass {
  private GreeterOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HelloRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.minhdtb.demo.protos.HelloRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string test1 = 1;</code>
     */
    java.lang.String getTest1();
    /**
     * <code>string test1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getTest1Bytes();

    /**
     * <code>string test2 = 2;</code>
     */
    java.lang.String getTest2();
    /**
     * <code>string test2 = 2;</code>
     */
    com.google.protobuf.ByteString
        getTest2Bytes();
  }
  /**
   * Protobuf type {@code com.minhdtb.demo.protos.HelloRequest}
   */
  public  static final class HelloRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.minhdtb.demo.protos.HelloRequest)
      HelloRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HelloRequest.newBuilder() to construct.
    private HelloRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HelloRequest() {
      test1_ = "";
      test2_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HelloRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              test1_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              test2_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.minhdtb.demo.protos.GreeterOuterClass.internal_static_com_minhdtb_demo_protos_HelloRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.minhdtb.demo.protos.GreeterOuterClass.internal_static_com_minhdtb_demo_protos_HelloRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest.class, com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest.Builder.class);
    }

    public static final int TEST1_FIELD_NUMBER = 1;
    private volatile java.lang.Object test1_;
    /**
     * <code>string test1 = 1;</code>
     */
    public java.lang.String getTest1() {
      java.lang.Object ref = test1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        test1_ = s;
        return s;
      }
    }
    /**
     * <code>string test1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTest1Bytes() {
      java.lang.Object ref = test1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        test1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEST2_FIELD_NUMBER = 2;
    private volatile java.lang.Object test2_;
    /**
     * <code>string test2 = 2;</code>
     */
    public java.lang.String getTest2() {
      java.lang.Object ref = test2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        test2_ = s;
        return s;
      }
    }
    /**
     * <code>string test2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTest2Bytes() {
      java.lang.Object ref = test2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        test2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTest1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, test1_);
      }
      if (!getTest2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, test2_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTest1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, test1_);
      }
      if (!getTest2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, test2_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest)) {
        return super.equals(obj);
      }
      com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest other = (com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest) obj;

      boolean result = true;
      result = result && getTest1()
          .equals(other.getTest1());
      result = result && getTest2()
          .equals(other.getTest2());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEST1_FIELD_NUMBER;
      hash = (53 * hash) + getTest1().hashCode();
      hash = (37 * hash) + TEST2_FIELD_NUMBER;
      hash = (53 * hash) + getTest2().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.minhdtb.demo.protos.HelloRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.minhdtb.demo.protos.HelloRequest)
        com.minhdtb.demo.protos.GreeterOuterClass.HelloRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.minhdtb.demo.protos.GreeterOuterClass.internal_static_com_minhdtb_demo_protos_HelloRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.minhdtb.demo.protos.GreeterOuterClass.internal_static_com_minhdtb_demo_protos_HelloRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest.class, com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest.Builder.class);
      }

      // Construct using com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        test1_ = "";

        test2_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.minhdtb.demo.protos.GreeterOuterClass.internal_static_com_minhdtb_demo_protos_HelloRequest_descriptor;
      }

      @java.lang.Override
      public com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest getDefaultInstanceForType() {
        return com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest build() {
        com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest buildPartial() {
        com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest result = new com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest(this);
        result.test1_ = test1_;
        result.test2_ = test2_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest) {
          return mergeFrom((com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest other) {
        if (other == com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest.getDefaultInstance()) return this;
        if (!other.getTest1().isEmpty()) {
          test1_ = other.test1_;
          onChanged();
        }
        if (!other.getTest2().isEmpty()) {
          test2_ = other.test2_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object test1_ = "";
      /**
       * <code>string test1 = 1;</code>
       */
      public java.lang.String getTest1() {
        java.lang.Object ref = test1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          test1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string test1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTest1Bytes() {
        java.lang.Object ref = test1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          test1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string test1 = 1;</code>
       */
      public Builder setTest1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        test1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string test1 = 1;</code>
       */
      public Builder clearTest1() {
        
        test1_ = getDefaultInstance().getTest1();
        onChanged();
        return this;
      }
      /**
       * <code>string test1 = 1;</code>
       */
      public Builder setTest1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        test1_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object test2_ = "";
      /**
       * <code>string test2 = 2;</code>
       */
      public java.lang.String getTest2() {
        java.lang.Object ref = test2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          test2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string test2 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTest2Bytes() {
        java.lang.Object ref = test2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          test2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string test2 = 2;</code>
       */
      public Builder setTest2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        test2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string test2 = 2;</code>
       */
      public Builder clearTest2() {
        
        test2_ = getDefaultInstance().getTest2();
        onChanged();
        return this;
      }
      /**
       * <code>string test2 = 2;</code>
       */
      public Builder setTest2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        test2_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.minhdtb.demo.protos.HelloRequest)
    }

    // @@protoc_insertion_point(class_scope:com.minhdtb.demo.protos.HelloRequest)
    private static final com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest();
    }

    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HelloRequest>
        PARSER = new com.google.protobuf.AbstractParser<HelloRequest>() {
      @java.lang.Override
      public HelloRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HelloRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.minhdtb.demo.protos.GreeterOuterClass.HelloRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HelloReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.minhdtb.demo.protos.HelloReply)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.minhdtb.demo.protos.HelloReply}
   */
  public  static final class HelloReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.minhdtb.demo.protos.HelloReply)
      HelloReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HelloReply.newBuilder() to construct.
    private HelloReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HelloReply() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HelloReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.minhdtb.demo.protos.GreeterOuterClass.internal_static_com_minhdtb_demo_protos_HelloReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.minhdtb.demo.protos.GreeterOuterClass.internal_static_com_minhdtb_demo_protos_HelloReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.minhdtb.demo.protos.GreeterOuterClass.HelloReply.class, com.minhdtb.demo.protos.GreeterOuterClass.HelloReply.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.minhdtb.demo.protos.GreeterOuterClass.HelloReply)) {
        return super.equals(obj);
      }
      com.minhdtb.demo.protos.GreeterOuterClass.HelloReply other = (com.minhdtb.demo.protos.GreeterOuterClass.HelloReply) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.minhdtb.demo.protos.GreeterOuterClass.HelloReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.minhdtb.demo.protos.HelloReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.minhdtb.demo.protos.HelloReply)
        com.minhdtb.demo.protos.GreeterOuterClass.HelloReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.minhdtb.demo.protos.GreeterOuterClass.internal_static_com_minhdtb_demo_protos_HelloReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.minhdtb.demo.protos.GreeterOuterClass.internal_static_com_minhdtb_demo_protos_HelloReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.minhdtb.demo.protos.GreeterOuterClass.HelloReply.class, com.minhdtb.demo.protos.GreeterOuterClass.HelloReply.Builder.class);
      }

      // Construct using com.minhdtb.demo.protos.GreeterOuterClass.HelloReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.minhdtb.demo.protos.GreeterOuterClass.internal_static_com_minhdtb_demo_protos_HelloReply_descriptor;
      }

      @java.lang.Override
      public com.minhdtb.demo.protos.GreeterOuterClass.HelloReply getDefaultInstanceForType() {
        return com.minhdtb.demo.protos.GreeterOuterClass.HelloReply.getDefaultInstance();
      }

      @java.lang.Override
      public com.minhdtb.demo.protos.GreeterOuterClass.HelloReply build() {
        com.minhdtb.demo.protos.GreeterOuterClass.HelloReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.minhdtb.demo.protos.GreeterOuterClass.HelloReply buildPartial() {
        com.minhdtb.demo.protos.GreeterOuterClass.HelloReply result = new com.minhdtb.demo.protos.GreeterOuterClass.HelloReply(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.minhdtb.demo.protos.GreeterOuterClass.HelloReply) {
          return mergeFrom((com.minhdtb.demo.protos.GreeterOuterClass.HelloReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.minhdtb.demo.protos.GreeterOuterClass.HelloReply other) {
        if (other == com.minhdtb.demo.protos.GreeterOuterClass.HelloReply.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.minhdtb.demo.protos.GreeterOuterClass.HelloReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.minhdtb.demo.protos.GreeterOuterClass.HelloReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.minhdtb.demo.protos.HelloReply)
    }

    // @@protoc_insertion_point(class_scope:com.minhdtb.demo.protos.HelloReply)
    private static final com.minhdtb.demo.protos.GreeterOuterClass.HelloReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.minhdtb.demo.protos.GreeterOuterClass.HelloReply();
    }

    public static com.minhdtb.demo.protos.GreeterOuterClass.HelloReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HelloReply>
        PARSER = new com.google.protobuf.AbstractParser<HelloReply>() {
      @java.lang.Override
      public HelloReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HelloReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.minhdtb.demo.protos.GreeterOuterClass.HelloReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_minhdtb_demo_protos_HelloRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_minhdtb_demo_protos_HelloRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_minhdtb_demo_protos_HelloReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_minhdtb_demo_protos_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rGreeter.proto\022\027com.minhdtb.demo.protos" +
      "\",\n\014HelloRequest\022\r\n\005test1\030\001 \001(\t\022\r\n\005test2" +
      "\030\002 \001(\t\"\014\n\nHelloReply2c\n\007Greeter\022X\n\010SayHe" +
      "llo\022%.com.minhdtb.demo.protos.HelloReque" +
      "st\032#.com.minhdtb.demo.protos.HelloReply\"" +
      "\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_minhdtb_demo_protos_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_minhdtb_demo_protos_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_minhdtb_demo_protos_HelloRequest_descriptor,
        new java.lang.String[] { "Test1", "Test2", });
    internal_static_com_minhdtb_demo_protos_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_minhdtb_demo_protos_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_minhdtb_demo_protos_HelloReply_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
